// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_genpass

import (
	context "context"

	service "github.com/ThienKim52/golang-dev/internal/app/service"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheckService is an autogenerated mock type for the HealthCheckService type
type HealthCheckService struct {
	mock.Mock
}

// GetHealthCheck provides a mock function with given fields: ctx
func (_m *HealthCheckService) GetHealthCheck(ctx context.Context) (service.HealthCheckResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthCheck")
	}

	var r0 service.HealthCheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.HealthCheckResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.HealthCheckResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(service.HealthCheckResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthCheckService creates a new instance of HealthCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckService {
	mock := &HealthCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
