// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_genpass

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LinkService is an autogenerated mock type for the LinkService type
type LinkService struct {
	mock.Mock
}

// GetLinkFromCode provides a mock function with given fields: ctx, code
func (_m *LinkService) GetLinkFromCode(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkFromCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenURL provides a mock function with given fields: ctx, url, exp
func (_m *LinkService) ShortenURL(ctx context.Context, url string, exp time.Duration) (string, error) {
	ret := _m.Called(ctx, url, exp)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, url, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, url, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, url, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinkService creates a new instance of LinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkService {
	mock := &LinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
