name: cd-pipeline
on:
  workflow_run:
    workflows: ["ci-pipeline"]
    types:
    - completed

jobs:
  cd_pipeline:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        working-directory: /root/bookmark-deployment
        run: |
          echo "Deploying application ... "
          git pull
          docker rm -f bookmark-service || true
          docker-compose pull bookmark_service
          docker-compose up -d bookmark_service
          docker system prune -f  

          